import type { RouterConfig } from "./schema.ts";

export const DEFAULT_ROUTER_CONFIG: RouterConfig = {
	version: 1,
	enabled: true,
	profile: "balanced",
	granularity: "run",
	candidateSource: "pi_enabled_authenticated",
	fallbackWhenNoCandidates: "current_model",
	showExplanations: true,
	includeModels: [],
	excludeModels: ["model-router/*"],
	complexity: {
		thresholds: { trivialMax: 0.2, simpleMax: 0.38, moderateMax: 0.58, complexMax: 0.78 },
		qualityFloor: { trivial: 0.2, simple: 0.4, moderate: 0.6, complex: 0.78, critical: 0.9 },
		reliabilityFloor: { trivial: 0.9, simple: 0.93, moderate: 0.95, complex: 0.97, critical: 0.99 },
	},
	profiles: {
		balanced: {
			maxCostRatio: 1,
			maxP95LatencyRatio: 1,
			weights: { quality: 0.55, reliability: 0.2, cost: 0.15, latency: 0.1 },
		},
		cost_first: {
			maxP95LatencyRatio: 1.5,
			weights: { quality: 0.25, reliability: 0.15, cost: 0.5, latency: 0.1 },
		},
		latency_first: {
			maxCostRatio: 1.25,
			weights: { quality: 0.25, reliability: 0.15, cost: 0.1, latency: 0.5 },
		},
		quality_first: {
			maxCostRatio: 2,
			maxP95LatencyRatio: 2,
			weights: { quality: 0.7, reliability: 0.2, cost: 0.05, latency: 0.05 },
		},
	},
	modelProfiles: {},
	classifier: {
		enabled: false,
		maxEstimatedCostUsd: 0.001,
		maxPromptChars: 4_000,
		timeoutMs: 10_000,
	},
	learning: {
		enabled: true,
		halfLifeDays: 30,
		rawRetentionDays: 90,
		projectOverlayMinSamples: 20,
		projectOverlayFullWeightSamples: 50,
		qualityPriorStrength: 4,
		reliabilityPriorMean: 0.97,
		reliabilityPriorStrength: 20,
		autoExplorationRate: 0.05,
	},
	rollout: {
		automatic: true,
		initialStage: "shadow",
		shadowMinCompleted: 100,
		shadowMinQualityLabels: 10,
		minimumObservationCompleteness: 0.9,
		exploreTreatmentRate: 0.2,
		exploreMinTreatment: 100,
		exploreMinControl: 100,
		exploreMinDays: 7,
		exploreMinQualityLabelsPerArm: 10,
		nonInferiorityProbability: 0.95,
		maxReliabilityRegression: 0.01,
		maxQualityRegression: 0.03,
		requiredCostOrLatencyImprovement: 0.1,
		softCostLatencyRegression: 0.2,
	},
	critical: {
		minimumReliabilityObservations: 50,
		minimumHumanValidatorLabels: 20,
		minimumReliabilityMean: 0.99,
		minimumQualityMean: 0.9,
	},
	judge: {
		enabled: false,
		sampleRate: 0.05,
		maxCostPerEvaluationUsd: 0.005,
		maxDailyCostUsd: 0.25,
		timeoutMs: 30_000,
		excludeTiers: ["critical"],
		maxPromptChars: 8_000,
		maxOutputChars: 12_000,
		minimumCalibrationPairs: 30,
		maxCalibrationMae: 0.2,
		maxCalibrationBias: 0.15,
	},
	virtualProvider: {
		enabled: true,
		maxFallbacksBeforeOutput: 1,
		switchMinimumUtilityGain: 0.15,
		contextWindow: 128_000,
		maxTokens: 16_384,
	},
	storage: {
		enabled: true,
		busyTimeoutMs: 250,
	},
	telemetry: {
		enabled: false,
	},
};
